name: Build DEB Package

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-deb:
    name: Build DEB Package
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: src-tauri

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf

      - name: Install frontend dependencies
        run: npm ci

      - name: Build frontend
        run: npm run build

      - name: Build Tauri DEB package
        run: npm run tauri build -- --bundles deb

      - name: Find DEB package
        id: find_deb
        run: |
          DEB_PATH=$(find src-tauri/target/release/bundle/deb -name "*.deb" | head -1)
          echo "deb_path=$DEB_PATH" >> $GITHUB_OUTPUT
          echo "deb_name=$(basename $DEB_PATH)" >> $GITHUB_OUTPUT

      - name: Upload DEB artifact
        uses: actions/upload-artifact@v4
        with:
          name: egadsync-deb-${{ github.sha }}
          path: ${{ steps.find_deb.outputs.deb_path }}
          retention-days: 30

      - name: Create Release Info
        run: |
          echo "## Build Information" > build-info.md
          echo "- **Commit:** ${{ github.sha }}" >> build-info.md
          echo "- **Branch:** ${{ github.ref_name }}" >> build-info.md
          echo "- **Build Date:** $(date -u)" >> build-info.md
          echo "- **DEB Package:** ${{ steps.find_deb.outputs.deb_name }}" >> build-info.md

      - name: Upload Build Info
        uses: actions/upload-artifact@v4
        with:
          name: build-info-${{ github.sha }}
          path: build-info.md
          retention-days: 30